<x-landing-layout>
    <x-landing.navbar/>
    <x-landing.display/>
    <x-landing.about_us/>
    <x-landing.product/>
    <x-landing.ballon/>
    <x-landing.argument/>
    <x-landing.contact/>
    <x-landing.footer/>
</x-landing-layout>